print("Tabela verdade")

print("\nOperador 'e':")
print(True, "e", True, "=", (True and True))
print(True, "e", False, "=", (True and False))
print(False, "e", True, "=", (False and True))
print(True, "e", True, "=", (False and False))
print("\nOperador 'ou':")
print(True, "ou", True, "=", (True or True))
print(True, "ou", False, "=", (True or False))
print(False, "ou", True, "=", (False or True))
print(True, "ou", True, "=", (False or False))
print("\nOperador 'não':")
print(True, "negado =",(not True))
print(False, "negado =", (not False))
